services:
  - type: web
    name: fastshare-stremio-addon
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FASTSHARE_PLAYBACK_MODE
        value: direct_stream
